v0.7.8 - bug with messages fixed
cloudblue/connect-extension-telegram-notifications pull request #5
Opened 2022-11-08 13:13 UTC by Sainomori

2022-11-08 17:33 UTC, marcserrat approved these changes

2022-11-11 02:32 UTC, Sainomori commented
<img width="318" alt="image" src="https://user-images.githubusercontent.com/328337/201249697-881db08e-64ac-4cad-b0fd-d34b0f76fd96.png">
<img width="326" alt="image" src="https://user-images.githubusercontent.com/328337/201249739-6d388221-a3bb-4280-88d4-6efd5b8c91c7.png">
<img width="370" alt="image" src="https://user-images.githubusercontent.com/328337/201249791-691f4da4-9f60-4f6d-b810-2ef6a5bb7dac.png">
<img width="489" alt="image" src="https://user-images.githubusercontent.com/328337/201249845-3c7ece9e-c57e-4880-b2a1-08ede4aa0143.png">

2022-11-11 08:13 UTC, marcserrat approved these changes

2022-11-11 08:13 UTC, marcserrat commented on docker-compose.yml
> +    image: cloudblueconnect/connect-extension-runner:26.36
Why you don't move to new schema using a Dockerfile?? As a sample shall look like bootstraped with our CLI

2022-11-11 08:18 UTC, ffaraone requested changes
Can you also rename `connect_telegram_ext.models.TestMessagePayload` to a name that don't start with `Test` so we remove this annoying warning that pytest emits ?
Thanks!

2022-11-11 08:18 UTC, ffaraone commented on connect_telegram_ext/models.py
> +    message_callback: Callable[[any, ConnectClient, dict], str]
This `any` is not `typing.Any`, it is the built-in `any` function.

2022-11-11 08:18 UTC, ffaraone commented on connect_telegram_ext/messages.py
> +    message_template = getattr(
```
message_template = getattr(
    Messages,
    f"{event.name.upper()}_{request[event.status_filed]}",
    getattr(
        Messages,
        f"{event.name.upper()}",
        Messages.DEFAULT_MESSAGE,
    )
)
```

2022-11-11 12:58 UTC, marcserrat approved these changes

2022-11-11 13:04 UTC, ffaraone approved these changes

2022-11-11 13:04 UTC, merged